#include <iostream>
#include <iomanip>
using namespace std;

int main(){

//Example 1
/*
int b = 1;
while(b < 5){
    cout << " two " << b<<endl;
    b++;
}
=============end=========*/

//Example 2
/*
int x = 0;
int condition;
cout << " Enter your condition : "; cin >> condition; cout <<endl;

while(x < condition){
    cout << " one : " << x <<endl;
    x++;
}
=======end=========*/

//Example3 while and switch
/*
int i = 0;
int condition;
cout << "\n Insert your condition : "; cin >> condition; cout <<endl;

while (i < condition){

    cout << " The while loop is: " << i <<endl;
    i++;

    if(i == 5){
        break;
    }
}

===========end=================*/

//Example 4 continue with while
/*
int condition, i=0;
cout << " Insert your condition : "; cin >> condition; cout << endl;

while(i< condition)
{

i++; // when u are using continue make sure the increamentation remain at the top

    if(i == 5){
        continue;
    }

  cout << " The loop is : " << i <<endl; //also the output should be at the bottom
}
=================end================*/



//Example 5
/*
int password = 123, input_pass;
string name= "john", input_name;

cout << " Enter your name : "; cin >> name;cout <<endl;
cout << " Enter your password : "; cin >> input_pass; cout<<endl;

while((input_name != name) && (input_pass != password)){
    cout << " Your Password or name is incorrect.\n";
    cout << " Try Again?\n";

    if(input_name != name)
    {
        cout << " Incorrect name try Again : \n";
        cout << " Enter Your Name : "; cin >> input_name;cout <<endl;
        cout << " The name you provide is correct thank you!!\n";

    }
    if(input_pass != password)
    {
        cout << " Incorrect password try again!! \n";
        cout << " Enter Your  password : "; cin >> input_pass; cout <<endl;
        cout << " Your password is correct this time ";

    }

}
cout << " Password and name successfully!!! \n";
*/



//Example 6 this prog collect as many time it can stopped when the user insert 0
/*
int collect;
int sum = 0;
int counter = 0;
double average;

while( counter <= collect){

    cout << " Enter your days : "; cin >> collect; cout <<endl;
    sum = sum + collect;

    counter ++;
}
 cout << " The Answer is : " << sum <<endl;

=============end===========*/


/*
string Name;
int NumberOfVolunteers;
int NumberOfBoxSold;
int TotalNumberOfBoxSold = 0;
double CostOfOneBox;
int counter = 0;
double store;


cout << " Enter the Number of Volunteers : "; cin >> NumberOfVolunteers; cout <<endl;


while(counter <= NumberOfVolunteers){

    cout << " Enter your name : "; cin >> Name; cout << endl;
    cout << " Enter the number of box sold : "; cin >> NumberOfBoxSold; cout <<endl;

     TotalNumberOfBoxSold = TotalNumberOfBoxSold + NumberOfBoxSold;

     cout << " The name is " << Name <<endl;
     cout << " Box Sold : " << NumberOfBoxSold <<endl;

     counter ++;

}

cout << " The Total is : " << TotalNumberOfBoxSold <<"\n\n";

cout << " Enter the price of each box : "; cin >> CostOfOneBox; cout <<endl;
cout << " Total R" << TotalNumberOfBoxSold * CostOfOneBox;



string name;
int volunteers, counter = 0, NumberOf_Items_sold, Total = 0;
double average;

cout << " Enter The Number : "; cin >> volunteers; cout<<endl;

while (counter <= volunteers){

    cout << " Enter Your Name "; cin >> name; cout <<endl;
    cout << " Enter the number of items sold : "; cin >> NumberOf_Items_sold;
    cout <<endl;

    Total = Total + NumberOf_Items_sold;
    counter++;
}

cout << " Display the Total : " << Total; cout <<endl;
average = Total / volunteers;
cout << " Average is " << average<<endl;
*/



//Example 8
//Student at the midle school volunteered to sell fresh backed cookies to raise funds to increase the number of the computer lab
// each student reported the number of boxes sold. we will write  aprogram that will output the total number of boxes of cookies sold,the total revenue
//generated by the selling the cookies,and the average of number of the boxes sold by each student in the following form:
//StudentName, NumberOf Boxes

/*
int st_volunteers, counter = 0,Result, NumberOf_box_sold, Total_Revenue = 0;
double Average_per_St,Cost_of_1Box = 9.99;

string Each_st_name;


cout << fixed <<showpoint << setprecision(2);
cout << " Enter The Number of student who volunteer : "; cin >> st_volunteers; cout <<endl;

while(counter <= st_volunteers){

    cout << " Enter your Student Name : "; cin >> Each_st_name; cout <<endl;
    cout << " Enter the number of box sold : "; cin >> NumberOf_box_sold; cout <<endl;


    Result = Cost_of_1Box * NumberOf_box_sold;

    Total_Revenue = Total_Revenue + NumberOf_box_sold;

    cout << " The name is : " << Each_st_name<<endl;
    cout << " The number of boxes sold is : " << NumberOf_box_sold <<endl;
    cout << " The Money Makes with all sells : R" << Result <<"\n\n";

    counter++;
}

cout << "\n The Total of all the boxes sold are : " << Total_Revenue<<endl;

 Average_per_St = Total_Revenue / st_volunteers;
cout << " The Average is : " << Average_per_St<<endl;

===============end===============*/

/*
char sentinel;
int counter = 0, num1, num2,sum;

cout << " Enter a sentinel value : "; cin >> sentinel; cout<<endl;

while (counter < 3){

    if(sentinel == 'S' || sentinel == 's')
    {
        cout << " Enter num1 and num2 : "; cin >> num1 >> num2; cout <<endl;
        sum = num1 + num2;
        cout << " The sum of the 2 number is : " << sum <<endl;

    }

    else if (sentinel == 'a' || sentinel =='b'){

            cout << " Enter num1 and num2 : "; cin >> num1 >> num2; cout <<endl;
        sum = num1 * num2;
        cout << " The product is : " << sum <<"\n\n";


    }
    else{
        cout << " you input the wrong character Try again? latter \n\n";
    }

    counter++;


}
===========end============*/



int Result, num, num1;
char latter;

cout << " Enter Any character : "; cin >> latter; cout <<endl;

while ( latter != 'Y' || latter != 'y' )
{
    cout << " Enter 2 number : " ; cin >> num >> num1; cout <<endl;
    Result = num - num1;
    cout << " The result is : " << Result <<endl;


    if(latter == 'Y' || latter == 'y'){
        cout << " Enter 2 numbers : " ; cin >> num >> num1; cout <<endl;
        Result = num+num1;
        cout << " the result is : " << Result<<endl;

    }


   break;
}




return 0;
}
